# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maciej A. Czyzewski
tagline:          'Blog'
description:      'Programmer & Designer'
url:              http://MaciejCzyzewski.github.io

author:
  name:           'Maciej A. Czyzewski'
  url:            http://MaciejCzyzewski.github.io

paginate:         5
