# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maciej A. Czyżewski
tagline:          'Blog'
description:      'Programmer & Designer'
url:              http://MaciejAnthonyCzyzewski.github.io

author:
  name:           'Maciej A. Czyżewski'
  url:            http://MaciejAnthonyCzyzewski.github.io

paginate:         5
