markdown:           redcarpet
highlighter:        pygments
lsi:                false
excerpt_separator:  "\n\n"

url:                http://maciejczyzewski.me
name:               $ touch 'Maciej A. Czyzewski'
description:        "Software engineer, hacker, and design enthusiast."

timezone:           Europe/Oslo