# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Maciej Czyżewski
tagline:          'Blog'
description:      'Programmer & Designer.'
url:              http://MaciejCzyzewski.github.io

author:
  name:           'Maciej Czyżewski'
  url:            http://MaciejCzyzewski.github.io

paginate:         5