timezone:     Europe/Oslo

# Basic
url:          https://maciejczyzewski.github.io/
title:        Maciej A. Czyzewski on the Web
description:  "Software engineer, hacker and design enthusiast."

# SEO
logo:                     /assets/images/czyzewski.png
google_site_verification: HBawTMww3xGdm4ZIKokBD8_Bx3YudVqrv1PISdhnthE

# Social
twitter:
  username:   _czyzewski
github:
  username:   maciejczyzewski

# Jekyll
markdown:     kramdown
highlighter:  rouge
include:      ["_pages"]

# Compress
compress_html:
  clippings:  all
  comments:   ["<!-- ", " -->"]
  blanklines: false
  startings:  [html, head, body]

# Stylesheets
sass:
  sass_dir:   _sass/
  style:      compressed

# Rubygems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
