markdown:           redcarpet
highlighter:        pygments
lsi:                false
excerpt_separator:  "\n\n"

url:                http://maciejczyzewski.me
name:               Maciej A. Czyzewski on the Web
description:        "Software engineer, hacker, and design enthusiast."

timezone:           Europe/Oslo